export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';

export const FETCH_WEATHER_DATA_FAIL = 'FETCH_WEATHER_DATA_FAIL';

export const SET_WEATHER_ERROR = 'SET_WEATHER_ERROR';

export const SET_FORECAST_ERROR = 'SET_FORECAST_ERROR';

export const ADD_CITY_TO_HISTORY = 'ADD_CITY_TO_HISTORY';

export const FETCH_FORECAST_DATA_SUCCESS = 'FETCH_FORECAST_DATA_SUCCESS';

export const FETCH_FORECAST_DATA_FAIL = 'FETCH_FORECAST_DATA_FAIL';

export const SET_FORECAST_INTO_HOUR_VERSION = 'SET_FORECAST_INTO_HOUR_VERSION';

export const DELETE_FORECAST_DATA = 'DELETE_FORECAST_DATA';
